/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_tests.check" instead.
 */

#include <check.h>

#include "../engine/math/s21_matrix4x4.h"
#include "matrix-lib/s21_matrix.h"

START_TEST(degree_to_radian)
{
float real_result = s21_degree_to_radian(45.0f);
float expected_result = 0.78539825;
ck_assert_ldouble_eq_tol(real_result, expected_result, 1e-6);

}
END_TEST

START_TEST(scale_matrix_reference)
{
vector size = { 0.5f, 0.5f, 0.5f, 1.0f };
matrix4x4 real_matrix = s21_scale_matrix_reference(size);
matrix_t matrix_1;
s21_create_matrix(4, 4, &matrix_1);
for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 3; j++) {
        matrix_1.matrix[i][j] = real_matrix.matrix[i][j];
    }
}
double real_result;
double expected_result = 0.125;
s21_determinant(&matrix_1, &real_result);;
ck_assert_ldouble_eq_tol(real_result, expected_result, 1e-6);
s21_remove_matrix(&matrix_1);

}
END_TEST

START_TEST(rotation_y_matrix_reference)
{
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, degree_to_radian);
    tcase_add_test(tc1_1, scale_matrix_reference);
    tcase_add_test(tc1_1, rotation_y_matrix_reference);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
